Feature/parsing logic sentences
wsi4/wsi_rezolucja pull request #13
Opened 2021-05-23 14:39 UTC by chlebnymaciej

Created parser for logic language

2021-05-23 15:31 UTC, debskipawel requested changes

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution.Tests/ParserTests/KeywordsTests/ConnecitvesTests.cs
> +﻿using Microsoft.VisualStudio.TestTools.UnitTesting;
Literówka w nazwie pliku i klasy

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Parser/ChainParser/IParseable.cs
> +namespace Resolution.Parser.ChainParser
Rozbiłbym to na kilka plików

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Parser/ChainParser/RecurSentenceParser.cs
> +    class RecurSentenceParser : AbstractParseable, ISentenceParseable
Zmieniłbym nazwę na pełne RecursiveSentenceParser

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Parser/ChainParser/RecurSentenceParser.cs
> +
Popraw te trzy newline'y w 132-134

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Parser/Decorators/DiseasesDeclarationSetDecorator.cs
> +            // maybve add some chain in here
Usuń proszę ten komentarz

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Parser/ChainParser/Keywords/BiconParser .cs
> +﻿using Resolution.Sentences;
Spacja na końcu nazwy pliku

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Parser/Decorators/ITextDecorator.cs
> +        string GetText();
Imo do zmiany na `string Text { get; }`, w implementacjach można dodać prywatnego settera

2021-05-23 15:31 UTC, debskipawel commented on Resolution/Resolution/Sentences/ComplexSentence.cs
> +
Newline do usunięcia

2021-05-24 11:49 UTC, chlebnymaciej commented on Resolution/Resolution.Tests/ParserTests/KeywordsTests/ConnecitvesTests.cs
> +﻿using Microsoft.VisualStudio.TestTools.UnitTesting;
fixed

2021-05-24 11:49 UTC, chlebnymaciej commented on Resolution/Resolution/Parser/ChainParser/RecurSentenceParser.cs
> +    class RecurSentenceParser : AbstractParseable, ISentenceParseable
done

2021-05-24 11:50 UTC, chlebnymaciej commented on Resolution/Resolution/Parser/ChainParser/RecurSentenceParser.cs
> +
done

2021-05-24 11:50 UTC, chlebnymaciej commented on Resolution/Resolution/Parser/Decorators/DiseasesDeclarationSetDecorator.cs
> +            // maybve add some chain in here
done

2021-05-24 11:51 UTC, chlebnymaciej commented on Resolution/Resolution/Parser/ChainParser/Keywords/BiconParser .cs
> +﻿using Resolution.Sentences;
done

2021-05-24 11:52 UTC, chlebnymaciej commented on Resolution/Resolution/Sentences/ComplexSentence.cs
> +
done

2021-05-24 12:00 UTC, chlebnymaciej commented on Resolution/Resolution/Parser/Decorators/ITextDecorator.cs
> +        string GetText();
done

2021-05-24 12:04 UTC, chlebnymaciej commented on Resolution/Resolution/Parser/ChainParser/IParseable.cs
> +namespace Resolution.Parser.ChainParser
done

2021-05-24 12:05 UTC, jankupis approved these changes

2021-05-24 12:07 UTC, debskipawel approved these changes
Teraz jest git

2021-05-24 12:22 UTC, merged