Implemented conjunction exclusion
wsi4/wsi_rezolucja pull request #8
Opened 2021-05-15 13:00 UTC by gardzielb

2021-05-15 14:37 UTC, debskipawel approved these changes
Git jest

2021-05-17 11:57 UTC, ArturChmura approved these changes
Jest co najmniej dobrze, jak nie lepiej

2021-05-17 16:53 UTC, debskipawel requested changes

2021-05-17 16:53 UTC, debskipawel commented on Resolution/TestProject2/TestProgram.cs
> +namespace TestProject
Tego już chyba miało tu nie być, nie?

2021-05-17 16:58 UTC, debskipawel approved these changes
Teraz jest klasa

2021-05-17 16:59 UTC, merged